import { Knex } from 'knex';

export async function seed(knex: Knex): Promise<void> {
  console.log('Creating seed places');
  await knex('place').insert([
    {
      name: 'The Plaza',
      description: 'Welcome to the plaza',
      slug: 'enter',
      assets_dir: '/enter/vrml/',
      world_filename: 'enter.wrl',
    },
    {
      name: 'Home 0',
      description: 'Welcome to home 0',
      slug: 'home00',
      assets_dir: '/000/',
      world_filename: 'home.wrl',
    },
    {
      name: 'Gameshow',
      description: 'Welcome to gameshow',
      slug: 'gameshow',
      assets_dir: '/gameshow/',
      world_filename: 'vrml/gameshow.wrl',
    },
    {
      name: 'fleamarket',
      description: 'fleamaket',
      slug: 'fleamarket',
      assets_dir: '/fleamarket/',
      world_filename: 'vrml/fleamarket.wrl',
    },
    {
      name: 'beach',
      description: 'beach',
      slug: 'beach',
      assets_dir: '/beach/',
      world_filename: 'vrml/beach.wrl',
    },
    {
      name: 'blackmarket',
      description: 'blackmarket',
      slug: 'blackmarket',
      assets_dir: '/blackmarket/',
      world_filename: 'vrml/blackmarket.wrl',
    },
    {
      name: 'mall',
      description: 'mall',
      slug: 'mall',
      assets_dir: '/shopping/',
      world_filename: 'vrml/shopping.wrl',
    },
    {
      name: 'bank',
      description: 'bank',
      slug: 'bank',
      assets_dir: '/bank/',
      world_filename: 'vrml/bank.wrl',
    },
    {
      name: 'employment',
      description: 'employment',
      slug: 'employment',
      assets_dir: '/employment/',
      world_filename: 'vrml/employment.wrl',
    },
    {
      name: 'outlands',
      description: 'outlands',
      slug: 'outlands',
      assets_dir: '/ne_game/',
      world_filename: 'vrml/ne_game.wrl',
    },
    {
      name: 'cafe',
      description: 'cafe',
      slug: 'cafe',
      assets_dir: '/cafe/',
      world_filename: 'vrml/cafe.wrl',
    },
    {
      name: 'library',
      description: 'library',
      slug: 'library',
      assets_dir: '/library/',
      world_filename: 'vrml/library.wrl',
    },
    {
      name: 'jail',
      description: 'jail',
      slug: 'jail',
      assets_dir: '/jail/',
      world_filename: 'vrml/jail.wrl',
    },
    {
      name: 'funpark',
      description: 'funpark',
      slug: 'funpark',
      assets_dir: '/funpark/',
      world_filename: 'vrml/funpark.wrl',
    },
    {
      name: 'waterpark',
      description: 'waterpark',
      slug: 'waterpark',
      assets_dir: '/waterpark/',
      world_filename: 'vrml/waterpark.wrl',
    },
    {
      name: 'themepark',
      description: 'themepark',
      slug: 'themepark',
      assets_dir: '/themepark/',
      world_filename: 'vrml/themepark.wrl',
    },
    {
      name: 'cityhall',
      description: 'cityhall',
      slug: 'cityhall',
      assets_dir: '/cityhall/',
      world_filename: 'vrml/cityhall.wrl',
    },
    {
      name: 'Performing Arts',
      description: 'Performing Arts',
      slug: 'theatre',
      assets_dir: '/theatre/',
      world_filename: 'vrml/theatre.wrl',
    },
    {
      name: 'The Pool',
      description: 'The Pool',
      slug: 'pool',
      assets_dir: '/pool/',
      world_filename: 'vrml/pool.wrl',
    },
    {
      name: 'The Stadium',
      description: 'The Stadium',
      slug: 'stadium',
      assets_dir: '/stadium/',
      world_filename: 'vrml/stadium.wrl',
    },
    {
      name: 'Post Office',
      description: 'Post Office',
      slug: 'postoffice',
      assets_dir: '/post/',
      world_filename: 'vrml/post.wrl',
    },
  ]);
}
