# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
          
      - name: running ssh remote commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          script_stop: true
          script: |
            git --version
            node --version
            npm --version
            cd ctr
            echo -e "\e[1;42m Pulling from github..."
            git pull origin master
            cd api
            echo -e "\e[1;42m Installing API packages..."
            npm install
            npm run build:prod
            cd ..
            cd spa
            echo -e "\e[1;42m Increment SPA minor version number..."
            npm version minor
            echo -e "\e[1;42m Installing SPA packages..."
            npm install
            echo -e "\e[1;42m Building SPA..."
            npm run build
